pipeline {
    agent any
    /*diff*/
    parameters {
        booleanParam(name: 'RC', defaultValue: false, description: 'Is this a Release Candidate?')
    }
    /*diff*/
    environment {
        VERSION = sh([ script: 'cd ./01/solution && npx -c \'echo $npm_package_version\'', returnStdout: true ]).trim()
        VERSION_RC = "rc.2"
    }
    stages {
        stage('Audit tools') {
            steps {
                auditTools()
            }
        }
        stage('Build') {
            /*diff*/
            environment {
                VERSION_SUFFIX = getVersionSuffix()
            }
            /*diff*/
            steps {
                dir('./01/solution') {
                    // echo "Building version ${VERSION} with suffix: ${VERSION_RC}"
                    echo "Building version ${VERSION} with suffix: ${VERSION_SUFFIX}"
                    sh '''
                        npm install
                        npm run build
                    '''
                }
            }
        }
        stage('Unit Test') {
            steps {
                dir('./01/solution') {
                    sh 'npm test'
                }
            }
        }
        /*diff*/
        stage('Publish') {
            when {
                expression { return params.RC }
            }
            steps {
                archiveArtifacts('01/solution/app/')
            }
        }
        /*diff*/
    }
}
void auditTools(){
                sh '''
                    git version
                    docker version
                    node --version
                    npm version
                '''
}

String getVersionSuffix(){
    if(params.RC){
        return "${env.VERSION_RC}+ci.${env.BUILD_NUMBER}";
    }else{
        return env.VERSION_RC;
    }
}