pipeline{
    agent any
    environment{
        DEMO='1.3'
    }
    
    stages{
        stage('stage-1'){
            steps{
                echo "This is a build numer $BUILD_NUMBER of demo $DEMO"
                sh '''
                echo "Using a multiline"
                chmod +x demo1/1,3/test.sh
                ./demo1/1,3/test.sh
                '''
            }
        }
    }
}